# Copyright 2023 StreamNative, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "oxia-cluster.coordinator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-coordinator
data:
  config.yaml: |
    namespaces:
      - name: default
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: bookkeeper
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: configuration-store
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: shared-bk
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: shared2-bk
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: shared3-bk
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: shared4-bk
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: shared5-bk
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: pulsar
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar1
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar2
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar3
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar4
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar5
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar6
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
      - name: test-pulsar7
        initialShardCount: {{ .Values.initialShardCount }}
        replicationFactor: {{ .Values.replicationFactor }}
    servers:
      {{- $vars := dict "name" .Release.Name "namespace" .Release.Namespace "public" .Values.server.ports.public "internal" .Values.server.ports.internal }}
      {{- range until (int .Values.server.replicas) }}
      - public: {{ $vars.name }}-{{ . }}.{{ $vars.name }}-svc.{{ $vars.namespace }}.svc.cluster.local:{{ $vars.public }}
        internal: {{ $vars.name }}-{{ . }}.{{ $vars.name }}-svc:{{ $vars.internal }}
      {{- end }}
